version: '3.8'

services:
  gateway:
    build:
      context: .                 # Byg Docker-image ud fra Dockerfile i rodmappen
    container_name: yarp-gateway
    ports:
      - "8080:80"                # Gør YARP Gateway tilgængelig på localhost:8080 → container:80
    restart: unless-stopped      # Genstart automatisk hvis den fejler
    networks:
      - sep4_network             # Tilføj til fælles netværk            

networks:
  sep4_network:
    driver: bridge               # Docker bridge-netværk
