version: '3.8'

services:
  gateway:
    build:
      context: .
    container_name: yarp-gateway
    ports:
      - "5107:5107"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - SEP4_NETWORK

networks:
  SEP4_NETWORK:
    external: true
